import Head from 'next/head'
import Hero from '@/components/Hero';
import CallOut from '@/components/CallOut';
import Testimonials from '@/components/Testimonials';
import CalloutFooter from '@/components/base/Footer';
import CallOutBackground from '@/components/CallOutBackground';
import FeatureCards from '@/components/FeatureCards';

export default function AboutPage() {
  return <>
    <Head>
      <title>About</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/logos/logo-temporal-no-copy.svg" />
    </Head>
    <main>
      {/* Hero */}
      <section>
        <Hero
          copy={{
            title: 'index',
            headline: 'About Temporal.',
            subhead: "We exist to shield developers from unnecessary risk and eliminate everything that gets in their way.  So they can focus on writing code and creating what’s next.",
          }}
          className="mt-24 mb-10 md:mt-[12.5rem] md:mb-20"
        />
      </section>

      <section>
        <CallOutBackground
          key={'distributedSystems'}
          copy={{
            headline: "We’re on a mission to  champion engineers  everywhere.",
            subhead: "We envision a world where developers are  empowered: influencing and leading the  direction of every business.",
          }}
          background="/images/backgrounds/about-callout.png"
          className="py-40 lg:pt-96 lg:pb-20 text-white"
        />
      </section>

      
       <section>
        <CallOut
          textAlign="left"
          key={'distributedSystems'}
          copy={{
            headline: "Temporal raises $100 Million Series B to invest in open source and developer communities.",
            linkCopy: "Read Max’s blog.",
            linkUrl: ""
          }}
          className="bg-gray-900 py-40 lg:py-80 text-white"
        />
      </section>

      <section className="mt-20 sm:mt-32 lg:mt-64 xxl:mt-96">
        <CallOut
          key={'code-and-scale'}
          textAlign="center"
          copy={{
            headline: '15 years  in the making.',
            subhead:
              'We’re growing at an incredible speed and want you to be a part of it. If none of these  positions are a fit for you, email careers@temporal.io describing your dream job.',
          }}
        />
        
      </section>

      <section className="mt-20 sm:mt-32 lg:mt-64 xxl:mt-96">
        <CallOut
          key={'code-and-scale'}
          textAlign="center"
          copy={{
            headline: 'Backed by',
          }}
        />
        
      </section>

      <section className="mt-20 sm:mt-32 lg:mt-64 xxl:mt-96">
        <CallOut
          key={'code-and-scale'}
          textAlign="center"
          copy={{
            headline: 'More about  Temporal.',
            subhead: 'Morbi nec leo sodales, ultricies lacus fringilla, tempus enim. Phasellus vel magna quis metus tempor tincidunt a ac erat. Quisque magna diam, euismod ut condimentum id.'
          }}
        />
        
      </section>

      <section className="mt-20 sm:mt-32 lg:mt-64 xxl:mt-96">
        <CallOut
          key={'code-and-scale'}
          textAlign="center"
          copy={{
            headline: 'Join  our team.',
            subhead: 'We’re growing at an incredible speed and want you to be a part of it. If none of these positions are a fit for you, email careers@temporal.io describing your dream job.'
          }}
        />

        <FeatureCards
          alignContent="start"
          cards={[
            {
              icon: '/images/icons/spiral.svg',
              alt: 'orbital icon',
              headline: 'Product',
              subhead:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec est non urna bibendum gravida. ',
              tags:['Product Management', 'Product Design', 'Front-End Platform', 'Technical Writing', 'Product Marketing', 'DevRel'],
              linkCopy: 'View Product job posings',
              linkUrl: "/",
            },
            {
              icon: '/images/icons/wrench.svg',
              alt: 'wrench icon',
              headline: 'Engineering',
              subhead:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec est non urna bibendum gravida. ',
              tags:['Backend Engineers', 'Software Engineers', 'Infrastructure', 'DevOps', 'Data Engineers', 'Language Runtime', 'IT Support Engineer'],
              linkCopy: 'View Engineering job posings',
              linkUrl: "/"
            },
            {
              icon: '/images/icons/brackets.svg',
              alt: 'code brackets icon',
              headline: 'Operations',
              subhead:
                'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec est non urna bibendum gravida. ',
              tags:['Recruiting', 'Human Resources'],
              linkCopy: 'View Operations job posings',
              linkUrl: "/"
            },
          ]}
          className=""
        />
        
      </section>



     










      <section className="bg-gray-900 text-white">
        <CallOut
          key={'userTrust'}
          textAlign="center"
          copy={{
            headline: 'People trust us.',
            subhead:
              'Not only do our users love us, but they also join us for our community events and share how they’re using us to grow their businesses.',
          }}
          className="text-center pt-32 pb-10"
        />
        <Testimonials
          cards={[
            {
              company: 'HashiCorp',
              quote:
                'HashiCorp needed to build long-running, reliable, fault-tolerant tasks for the HashiCorp Cloud Platform. Temporal’s technology satisfied all of these requirements out of the box and allowed our developers to focus on business logic.  Without Temporal’s technology, we would’ve spent a significant amount of time rebuilding Temporal and would’ve very likely done a worse job.',
              name: 'Mitchell Hashimoto',
              title: 'Co-founder, Hashicorp',
            },
            {
              company: 'Checkr',
              quote:
                'Developer happiness has increased. Thinking in terms of workflows and activities has clarified our product and allowed us to share workflow components with different teams.',
              name: 'Ben Jacobson',
              title: 'Staff Software Engineer, Checkr',
            },
            {
              company: 'Coinbase',
              quote:
                'Temporal maintains high reliability while providing tremendous visibility. Things we thought to be much more complex... feel much easier!',
              name: 'Anthony Dmitriyev',
              title: 'Software Engineer, Coinbase',
            },
            {
              company: 'Descript',
              quote:
                'A game changing revelation - Temporal gave us the ability to test our workflows with unit tests. JSON or YAML are completely untestable!',
              name: 'Nicolas Gere',
              title: 'Software Engineer, Descript',
            },
            {
              company: 'Box',
              quote:
                "The API gives you this illusion of single threaded execution... It's amazing.",
              name: 'Steven Cipolla',
              title: 'Senior Staff Software Engineer, Box',
            },
          ]}
        />

        <CalloutFooter />
      </section>

    </main>
  </>;
}