import Head from 'next/head';
import Hero from '@/components/Hero';
import styles from '@/styles/Home.module.css';
import ValueProps from '@/components/ValueProps';

export default function InTheWild() {
  return (
    <div className={styles.container}>
      <Head>
        <title>In The Wild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Hero copy={{}}/>
      </section>
      <section>
        <ValueProps copy={{ title: "here's some more props"}} />
      </section>
    </div>
  )
}
